### ISSUE TITLE
使用4.19版本内核导致无法开启ipvs

### ISSUE THREAD

**Issue by Lentil1016** [Lentil1016/kubeadm-ha#14]
由于最新稳定版4.19内核将nf_conntrack_ipv4更名为nf_conntrack，目前的kube-proxy不支持在4.19版本内核下开启ipvs
详情可以查看：https://github.com/kubernetes/kubernetes/issues/70304
对于该问题的修复10月30日刚刚合并到代码主干，所以目前还没有包含此修复的kubernetes版本发出
读者可以选择安装我提供的4.18版本内核，或者不开启IPVS
4.18版本内核RPM下载链接：https://pan.baidu.com/s/1dCeozuMRQ96MBBjGpf0cjA 提取码：3nqg

**Comment by Lentil1016** [comment]
fixed in kubernetes 1.13.0

**Comment by gouki777** [comment]
> fixed in kubernetes 1.13.0

kubernetes version (1.10.11 | 1.11.5) is fixed ?

**Comment by Lentil1016** [comment]
@gouki777 No, this fix haven't been cherry-picked into 1.12.x yet, and definitely not in 1.10.x or 1.11.x. You might want to upgrade to 1.13.0 to use `ipvs` feature.

**Comment by gouki777** [comment]
thank you.
