### ISSUE TITLE
如何去设置k8s 集群的时区呢

### ISSUE THREAD

**Issue by izern** [Lentil1016/kubeadm-ha#17]
主要是k8s 系统用的一些容器
例如scheduler，controller-manager，apiserver
尝试在官方镜像基础上， 配置/etc/localtime， 但并不是很好用
请问没有简便的方法？

**Comment by Lentil1016** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        您好
        
    参考该链接中提供的方法：https://github.com/kubernetes/kubernetes/issues/44815#issuecomment-297077509可以先将localtime制作成一个configmap，然后修改/etc/kubernetes/manifest中的编排文件，将configmap挂载为容器中的/etc/localtime文件祝好运
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                lentil1016
                            
                    
                        
                            
                                    lentil1016@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2018年11月21日 13:53，泽恩<notifications@github.com> 写道： 


主要是k8s 系统用的一些容器
例如scheduler，controller-manager，apiserver
尝试在官方镜像基础上， 配置/etc/localtime， 但并不是很好用
请问没有简便的方法？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by izern** [comment]
tks, 我试试。

**Comment by Lentil1016** [comment]
我假定这个Issue已经被解决，所以将关闭它，如果问题没有被解决，请Reopen it.

**Comment by arrowfeng** [comment]
> 主要是k8s 系统用的一些容器
> 例如scheduler，controller-manager，apiserver
> 尝试在官方镜像基础上， 配置/etc/localtime， 但并不是很好用
> 请问没有简便的方法？

我想问一下你解决了吗？ 怎么解决的？
