### ISSUE TITLE
各节点服务怎么重启？

### ISSUE THREAD

**Issue by ppabc** [Lentil1016/kubeadm-ha#18]
各节点服务怎么重启？
如果服务器节点挂了，怎么启动，重启了， dashboard.multi.io报Gateway Timeout错误

**Comment by Lentil1016** [comment]
Gateway timeout错误通常是因为容器没有启动或容器无法提供服务，请运行`kubectl get pods -n kube-system`查看你的容器运行状态，本项目为集群自动化部署，该问题与本项目无关，将被关闭，抱歉。
