### ISSUE TITLE
请问下为什么要用4.18版本内核？

### ISSUE THREAD

**Issue by ppabc** [Lentil1016/kubeadm-ha#19]
是因为 4.18内核，kube-proxy才能支持ipvs ?
CentOS Linux系统默认的 (3.10.0-693.el7.x86_64) 7 (Core)
这个不支持吗？3.10.0-693.el7.x86_64打个补丁 是否也可以 ？

还有个疑问，集群结构摘要没有看到traefik，是和lvs一起在load balance这层吗？

**Comment by Lentil1016** [comment]
首先3.10内核中有复数个Cgroup内存泄漏的bug。
并且3.10版本内核且缺少ip_vs_fo.ko模块，将导致kube-proxy无法开启ipvs模式。
查看[索引](https://rpmfind.net/linux/rpm2html/search.php?query=kmod(ip_vs_fo.ko))可知出现ip_vs_fo.ko模块的最早版本为3.19版本，这个内核版本在RedHat系列发行版的常见RPM源中是不存在的。当然是否要通过手工编译内核的方式采用依然是你的选择。
对于为何是特定的4.18版本，而不是更高版本，请参考 #14

**Comment by Lentil1016** [comment]
如果没有其他疑惑，烦请关闭这个问题

**Comment by ppabc** [comment]
谢谢
