### ISSUE TITLE
双网卡下会报这个错误

### ISSUE THREAD

**Issue by ppabc** [Lentil1016/kubeadm-ha#20]
[root@test111 kubeadm-ha]# cat cluster-info 

CP0_IP=192.168.56.104
CP0_HOSTNAME=test111
CP1_IP=192.168.56.105
CP1_HOSTNAME=test222
CP2_IP=192.168.56.107
CP2_HOSTNAME=test333
VIP=192.168.56.199
NET_IF=enp0s3
CIDR=192.168.0.0/16

![f20181127162850](https://user-images.githubusercontent.com/2290874/49068457-c1aead80-f261-11e8-9818-a0484396e04c.png)
![f20181127162919](https://user-images.githubusercontent.com/2290874/49068458-c1aead80-f261-11e8-988b-b0460078d7a6.png)
![f20181127162945](https://user-images.githubusercontent.com/2290874/49068459-c2474400-f261-11e8-924c-59e010732705.png)

**Comment by ppabc** [comment]
我配置用的是enp0s3网卡 ，为什么会用到 enp0s8 呢？

**Comment by Lentil1016** [comment]
请检查`calico`报错的机器上的默认路由，默认路由应当指向`enp0s3`网卡

**Comment by ppabc** [comment]
怎么查calico日志啊 ？是看calico的容器的日志吗 ？

**Comment by ppabc** [comment]
增加上面两行后，测试没问题
