### ISSUE TITLE
怎么实现安装coredns的

### ISSUE THREAD

**Issue by ppabc** [Lentil1016/kubeadm-ha#22]
看项目里面文件没有包含coredns，测试能装上coredns，咋实现的啊，能写几个文档说说嘛？

**Comment by Lentil1016** [comment]
[Deploying Kubernetes with CoreDNS using kubeadm](https://coredns.io/2018/01/29/deploying-kubernetes-with-coredns-using-kubeadm/)

**Comment by ppabc** [comment]
谢谢，原来coredns都已经变成默认了的啊
