### ISSUE TITLE
什么时候升级到v1.12.3啊?

### ISSUE THREAD

**Issue by aq2cn** [Lentil1016/kubeadm-ha#27]
Kubernetes首爆严重安全漏洞请升级Kubernetes
https://aqzt.com/5515.html
v1.12.1有这个漏洞吧？什么时候升级到v1.12.3啊?

**Comment by Lentil1016** [comment]
您好，建议参考[本文](https://www.kubernetes.org.cn/4948.html)直接使用1.13.0版本
如果想平滑升级，请在部署了私有仓库后，使用`kubeadm upgrade plan`计划升级

**Comment by Lentil1016** [comment]
- [Upgrading kubeadm HA clusters from v1.11 to v1.12](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha-1-12/)
- [Upgrading kubeadm HA clusters from v1.12 to v1.13](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha-1-13/)
