### ISSUE TITLE
traefik如何换成nginx呢？指导下

### ISSUE THREAD

**Issue by aq2cn** [Lentil1016/kubeadm-ha#29]
traefik如何换成nginx呢？我想把traefik-ingress-controller换成ingress-nginx可以换吗？
或者项目是否可以支持可以选择traefik还是nginx ?

**Comment by Lentil1016** [comment]
我没有提供Nginx ingress controller的编排文件，如果需要使用nginx，请直接卸载traefik，然后安装nginx。
安装nginx可能需要额外关注TLS相关配置，默认配置下dashboard可能无法正确透出。

**Comment by aq2cn** [comment]
能提供Nginx ingress controller的编排文件吗？

**Comment by Lentil1016** [comment]
抱歉，我不会在本项目中提供我没有测试过的编排文件，烦请自行在github上搜索

**Comment by aq2cn** [comment]
好的，感谢
