### ISSUE TITLE
请教下安装镜像问题

### ISSUE THREAD

**Issue by opcache** [Lentil1016/kubeadm-ha#37]
看了作者的kubeadm HA master(v1.11.0)集群搭建指南文章，其实说到
harbor只支持{hostname}/{project}/{image}:{tag}，所以k8s.gcr.io/pause:3.1一类的镜像放不进去。
作者安装的脚本和yamp编排文件中是否可以修改成{hostname}/{project}/{image}:{tag}这样的格式呢？
有办法吗？如果不能修改为什么呢？官网安装yaml限制了吗？这块不懂，请教一下

**Comment by Lentil1016** [comment]
理论上可以改，但我没有做过。
理论上你要是非想这样做，有两种方法：

第一种是在yaml生成前配置，yaml文件是由kubeadm自动生成的，其中镜像url是取了kubeadm-config里的`ClusterConfiguration.imageRepository: k8s.gcr.io`生成的，你或许可以尝试把`k8s.gcr.io`改成`gcr.io/google_container`试试，但我不确定可以。

至于kubeadm生成文件后手动去改文件理论上也并不是不可能，这些文件在`/etc/kubernetes/manifest`文件夹下，只要改完之后kubelet会自动加载。但这或许意味着一开始生成的URL是不对的，也就意味着集群初始化时是拉取不到镜像的，这或许会导致集群搭建失败。

另一方面，这个问题属于kubeadm，本项目中不再做进一步解答。
