### ISSUE TITLE
master01節點重啟后導致dashboard不能訪問問題

### ISSUE THREAD

**Issue by liujunfei980** [Lentil1016/kubeadm-ha#39]
非常感謝老師前幾天幫我解決了通過ingress方式訪問dashboard控制台問題，現在又遇到一個新問題，我在測試master節點高可用時，發現master01重啟后，導致上面的dashboard pod漂移到了worker節點，導致dashboard無法通過dashboard.multi.io域名訪問，這是不是CoreDNS解析的問題？

**Comment by Lentil1016** [comment]
您好

> 發現master01重啟后，導致上面的dashboard pod漂移到了worker節點，導致dashboard無法通過dashboard.multi.io域名訪問

首先需要说我没能复现出这个问题，我在3台master以外的一台worker上启动dashboard pod，然后将域名解析到某一个master上并访问，没有出现访问问题

这个问题有几个检查点：

1. 它经过了ingress，traefik负责将携带host header的http包转发到对应的容器IP上，而这个转换关系是traefik直接去apiserver取的，因此这里不会有DNS的问题。
2. 它经过了calico负责在各个机器上维护的tunl0路由规则，该规则负责将某个容器IP的包转发到该容器所在的机器上，你的情况中该步骤出问题的可能性比较大。
3. 它到达了指定Pod所在的机器，经过由calico负责维护的各个机器上的cali******精确路由规则转发到特定的Pod上。

检查路由的命令`route -n`，如果需要检查traefik是否记录了正确的解析规则，请访问traefik dashboard

**Comment by liujunfei980** [comment]
剛放假歸來，今天我在master01和worker02節點互相ping對方tunl0 網卡IP (master01:10.244.0.1  worker02:10.244.4.1)，剛開始互相ping不通，但過了一會卻可以互相ping通，dashboad就可以正常訪問了，感覺挺奇怪的，查看兩節點路由信息，如下：
master01路由信息：
[root@zz-k8s-master01 ~]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.206.132.1    0.0.0.0         UG    100    0        0 eth0
10.206.132.0    0.0.0.0         255.255.255.0   U     100    0        0 eth0
10.244.0.0      0.0.0.0         255.255.255.0   U     0      0        0 *
10.244.1.0      10.206.132.112  255.255.255.0   UG    0      0        0 tunl0
10.244.2.0      10.206.132.113  255.255.255.0   UG    0      0        0 tunl0
10.244.3.0      10.210.58.114   255.255.255.0   UG    0      0        0 tunl0
10.244.4.0      10.210.58.115   255.255.255.0   UG    0      0        0 tunl0
10.244.5.0      10.210.58.116   255.255.255.0   UG    0      0        0 tunl0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0

worker02路由信息：
[root@zd-os-k8s-compute02 ~]# route -n 
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.210.58.1     0.0.0.0         UG    0      0        0 eth0
10.210.58.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
10.244.0.0      10.206.132.111  255.255.255.0   UG    0      0        0 tunl0
10.244.1.0      10.206.132.112  255.255.255.0   UG    0      0        0 tunl0
10.244.2.0      10.206.132.113  255.255.255.0   UG    0      0        0 tunl0
10.244.3.0      10.210.58.114   255.255.255.0   UG    0      0        0 tunl0
10.244.4.0      0.0.0.0         255.255.255.0   U     0      0        0 *
10.244.4.2      0.0.0.0         255.255.255.255 UH    0      0        0 calicb653f88965
10.244.4.8      0.0.0.0         255.255.255.255 UH    0      0        0 cali807405b3a8e
10.244.4.9      0.0.0.0         255.255.255.255 UH    0      0        0 cali98e9aa906b8
10.244.5.0      10.210.58.116   255.255.255.0   UG    0      0        0 tunl0
169.254.169.254 10.210.58.100   255.255.255.255 UGH   0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0

**Comment by Lentil1016** [comment]
可能是由于虚IP的连接闪断造成的，我这里有的集群上也出现过这样的情况，我的情况中由于kube-proxy无法通过虚IP连接到APIserver，因此不能及时更新ipvs规则，导致旧的pod已经被销毁，但是新的路由规则却没有导入。APIserver连接节点时是通过真实的物理IP，所以调度不会出问题，但是kube-proxy在取找APIServer的时候会经过虚IP，最后虚IP闪断造成了问题。但为什么那个集群上会闪断我并不太清楚，我目前最好的猜测是那个集群是虚拟机环境，虚拟网关在处理VRRP的时候出了什么问题。

**Comment by Lentil1016** [comment]
如果没有更多问题的话，我会关闭这个问题，如果有需要的话可以重新开启 😄

**Comment by liujunfei980** [comment]
> 如果没有更多问题的话，我会关闭这个问题，如果有需要的话可以重新开启
多謝老師的指導，我這邊再找下具體的原因，現在發現一個規律，只要master節點ping不通worker節點，再去worker節點上ping 這個master節點就通了，虛擬VIP一直都很穩定，具體我再查下原因。
