### ISSUE TITLE
calico未知问题导致的nodePort失效，Traefik无法使用问题

### ISSUE THREAD

**Issue by iedwin** [Lentil1016/kubeadm-ha#40]
每次都完全删除/新建虚机，重装3次依然出现nodePort失效和Traefik无法使用的问题(之前也装过多次，并没有出现该问题，该问题是昨天的某一次重装开始就一直出现)：
1. nodePort：可以在每一个node上看到已经都在监听建立的nodePort了，但是该nodePort只在pod所在的node好用，其他node上均不好用。
2. Traefik也一样，只有域名指向pod所在的node才能访问到。

我猜测是calico的问题，但是看到包括calico在内的所有pod都是running没有问题的，所以我就想替换成flannel试试，但是很不幸，直接用项目主的yaml删除calico，并安装flannel失败，说是sandbox有问题。仔细看了看项目主的脚本，发现是在组ha之前就apply了calico，所以猜测是这里导致flannel无法使用。我又删掉、重建虚机，将项目主脚本中的apply calico换成apply flannel后，nodePort和ingress都可以正常运行了。

这里想请教项目主一个问题，你们私有云/公有云用k8s时，一般集群外访问应用，nodePort和Ingress应该指向那个master?因为slave容易down，所以我觉得不能指向slave，除非在公有云环境用SLB等LoadBalancer指向所有slave然后做健康检测。
您给出的方案是3个master，所以单指向哪个master都不行，你们是怎么做的？是把keepalived的虚拟IP配到公网上，还是在k8s前面再放一个haproxy呢？

**Comment by Lentil1016** [comment]
您好

> nodePort：可以在每一个node上看到已经都在监听建立的nodePort了，但是该nodePort只在pod所在的node好用，其他node上均不好用。

我怀疑并不一定是calico导致了这个问题。calico是CNI插件，它只负责在Pod启动时候负责在本机创建虚拟网卡设备和路由规则，而这个工作是在创建pod的时候就完成了的。其他包括nodePort监听和将请求转发到指定node的工作都是kube-proxy在负责。

下面的`cali82a42f8fee2`和`cali3048647e9dc`设备和指向它们的精细路由是由calico负责创建的，它们能够将从其他机器上发来的请求包分发到本机特定的容器上，如果calico是你的怀疑对象，请检查这些条目是否存在，如果不存在，我以为应当首先尝试从kube-proxy开始查找问题线索。

```
$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.130.29.1     0.0.0.0         UG    100    0        0 ens32
10.130.29.0     0.0.0.0         255.255.255.0   U     100    0        0 ens32
10.244.0.0      0.0.0.0         255.255.255.0   U     0      0        0 *
10.244.0.124    0.0.0.0         255.255.255.255 UH    0      0        0 cali82a42f8fee2
10.244.0.125    0.0.0.0         255.255.255.255 UH    0      0        0 cali3048647e9dc
10.244.1.0      10.130.29.81    255.255.255.0   UG    0      0        0 tunl0
10.244.2.0      10.130.29.82    255.255.255.0   UG    0      0        0 tunl0
172.96.0.0      0.0.0.0         255.255.128.0   U     0      0        0 docker0
```

还有哪些可以帮助理解这个问题的手段？

- 在宿主机监听calico虚拟设备的包
- 在宿主机监听默认路由指向的网卡(例如eth0)
- 在容器内监听eth0网卡
- 对比三者查看包是否到达本机，如果到达本机则检查在哪一环丢失，如果没到达本机查看kube-proxy日志

公有云上经常会限制使用虚IP，目前这个配置只在私有云上使用过。HTTP服务的高可用方法应该算是DNS负载均衡。

**Comment by iedwin** [comment]
@Lentil1016 感谢您的回答！
我会在下次重装的时候按照您的提示重新查看一下calico创建的这些路由规则。calico失效有可能是我昨天改动openstack的网络有关系，因为我想用openstack的一个外网网络池中的IP指向keepalived的虚拟IP，没配成功。
刚了解了一下DNS负载均衡，确实是HTTP HA一个很好的手段。如果是私有云环境下，没有这种靠谱的DNS,SLB之类的怎么办呢，而且可能面对的是4/7层负载均衡，是不是只能通过HAproxy来对后面的master做负载均衡/健康检测？

**Comment by Lentil1016** [comment]
@iedwin 抱歉，HAProxy我没有了解过，不过按官方的描述看来，它应该可以更好的满足你的需要

**Comment by iedwin** [comment]
@Lentil1016 好的，非常感谢！ : )

**Comment by liujunfei980** [comment]
> @Lentil1016 感谢您的回答！
> 我会在下次重装的时候按照您的提示重新查看一下calico创建的这些路由规则。calico失效有可能是我昨天改动openstack的网络有关系，因为我想用openstack的一个外网网络池中的IP指向keepalived的虚拟IP，没配成功。

你好！在openstack平台上使用keepalived虛擬IP確實有些問題，似乎不能進行vrrp通信，我之前也在openstack上安裝部署keepalived，但發現虛擬ip無法漂移，這個問題一直沒解決，最後只好將master節點換到hyper-v虛擬平台上，keepalived恢復正常，請問你的openstack平台上keepalived 虛擬ip通信問題解決了嗎？

**Comment by iedwin** [comment]
@liujunfei980 上次失败以后我并没有再去做尝试，所以现在我的整个k8s系统还是有单点问题。：（
延伸一下，我一直没想明白这种私有云集群外连接集群内POD的连接单点问题要如何解决，也想请教您一下该问题。
您看：
目前3个master只要不全down, k8s集群就不会down，这没有任何问题，但对于集群外应用的连接应该如何处理？假设某个POD开通了nodePort，集群外的应用想连集群内的这些POD应该是连某个k8s node的IP和nodePort。但是要连哪个node的IP呢？slave node本身就可能down肯定不合适，master也有可能down，所以感觉直接连谁的IP都不行。
我能想到的方案：
1. 利用外部的LoadBalancer。外部应用先连haproxy, 然后在haproxy上对slave/master node做健康检查，保证外部应用可以连上健康的node。但这样haproxy本身又成了单点，又得需要keepalived做热备，所以到最后还是得解决keepalived的VIP在集群外连接问题。
2. 回到keepalived的VIP外网连接，如果都是物理机环境的话，假设3台master都是双网卡，k8s集群内部需要用keepalived在eth0上做VIP让slave node连master node，在所有master的eth1上也要起另一套keepalived配上外网地址可访问的VIP，这样让外部应用直接连外网的keepalived的VIP貌似就能达到HA了，但是我不知道在外网IP上能不能配这种东西。。如果是openstack环境，这个外网映射就得需要放在openstack本身解决了。。
请问您有什么更好的可行方法吗？

**Comment by liujunfei980** [comment]
> @liujunfei980 上次失败以后我并没有再去做尝试，所以现在我的整个k8s系统还是有单点问题。：（
> 延伸一下，我一直没想明白这种私有云集群外连接集群内POD的连接单点问题要如何解决，也想请教您一下该问题。
> 您看：
> 目前3个master只要不全down, k8s集群就不会down，这没有任何问题，但对于集群外应用的连接应该如何处理？假设某个POD开通了nodePort，集群外的应用想连集群内的这些POD应该是连某个k8s node的IP和nodePort。但是要连哪个node的IP呢？slave node本身就可能down肯定不合适，master也有可能down，所以感觉直接连谁的IP都不行。
> 我能想到的方案：
> 
> 1. 利用外部的LoadBalancer。外部应用先连haproxy, 然后在haproxy上对slave/master node做健康检查，保证外部应用可以连上健康的node。但这样haproxy本身又成了单点，又得需要keepalived做热备，所以到最后还是得解决keepalived的VIP在集群外连接问题。
> 2. 回到keepalived的VIP外网连接，如果都是物理机环境的话，假设3台master都是双网卡，k8s集群内部需要用keepalived在eth0上做VIP让slave node连master node，在所有master的eth1上也要起另一套keepalived配上外网地址可访问的VIP，这样让外部应用直接连外网的keepalived的VIP貌似就能达到HA了，但是我不知道在外网IP上能不能配这种东西。。如果是openstack环境，这个外网映射就得需要放在openstack本身解决了。。
>    请问您有什么更好的可行方法吗？

你好！
針對第1個問題，我創建pod和service時，採用的方式是NodePort，代碼如下：
spec:
   ports:
   - name: myweb-svc
     port: 8080
     targetPort: 8080
     nodePort: 30080
   selector:
     app: myweb
   type: NodePort
這種方式部署應用的話，集群外部可以通過訪問任何一個salve節點IP進行業務訪問，但是這種方式缺點也很明顯，需要在k8s集群外部再搭建一套LoadBalancer對salve 節點做輪巡，不過看了一些其他資料，目前採用ingress方式部署比較好，通過域名映射訪問，將域名映射給多個salve 節點ip，讓外部用戶通過域名訪問，這樣就算其中一個salve節點宕機，也不會影響業務訪問，這樣就不需要在外部再搭建一套LoadBalancer。
針對第2個問題，目前我這邊還沒驗證雙網卡做k8s集群，但根據你部署情況，我對這個也比較有疑惑，我們這邊不同網段的用戶進行了隔離，不能互相訪問，後續如果採用雙網卡的話，是不是需要使用兩個keepalived vip地址呢？如果是兩個keepalived vip又該如何跟kube-apiserver進行通信？畢竟所有master節點都是通過調用kube-apiserver進行任務調用和創建。

**Comment by iedwin** [comment]
@Lentil1016 感谢你详尽的回答！
@liujunfei980 项目主说的很对，Ingress无法完全替代nodePort。所以在HA k8s集群环境下，负载均衡是必须的。
感谢两位的分享和解答，我觉得该问题可以关掉了。“：）
