### ISSUE TITLE
kubeadm init 执行报错问题

### ISSUE THREAD

**Issue by itiger-club** [Lentil1016/kubeadm-ha#46]
1、脚本版本1.11.0
2、cluster-info配置
<img width="243" alt="image" src="https://user-images.githubusercontent.com/24242501/51219698-fa6b2900-196c-11e9-9082-749c49f270da.png">
3、执行kubeadm提示如下异常，请问可能是什么原因导致？
<img width="585" alt="image" src="https://user-images.githubusercontent.com/24242501/51219493-26d27580-196c-11e9-92a8-acdf0e9442b5.png">

**Comment by Lentil1016** [comment]
![image](https://user-images.githubusercontent.com/12230071/51220015-75810f00-196e-11e9-97ea-d1d020ee595b.png)

**Comment by itiger-club** [comment]
没有找到问题，把所有配置相关的又检查了一边，看上去是没有连接到镜像，镜像能pull出来
应该如何去往下分析了

**Comment by Lentil1016** [comment]
kubeadm init命令在做完preflightcheck之后做的第一件事就是拉取镜像，你的kubeadm都已经走到kubelet连接失败了，镜像肯定早就拉取成功了。基于你的情况，我给出两点debug建议

- 检查防火墙
- 不要好高骛远
- 学习基本的kubeadm部署方法
- 不要执行你不知道是干什么用的命令

**Comment by lanmingle** [comment]
``` bash

# kubeadm config print init-defaults
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
imageRepository: k8s.gcr.io
# imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers

```

**Comment by Lentil1016** [comment]
如有需要请重新开启
