### ISSUE TITLE
kube-proxy在ipvs mode下定时更新ipvs规则的疑问

### ISSUE THREAD

**Issue by opcache** [Lentil1016/kubeadm-ha#48]
kube-proxy在ipvs mode下定时更新ipvs规则的疑问，
我手动添加了一些LVS规则，貌似会被kube-proxy给清理掉，为什么会清理掉呢？
kube-proxy不是刷新部分LVS规则？如果我需要手动加一些LVS规则，有怎么做呢？
请教一下，谢谢！

**Comment by Lentil1016** [comment]
https://github.com/Lentil1016/kubeadm-ha/issues/47#issuecomment-455017491

**Comment by opcache** [comment]
非常感谢，我去试试，找找资料！
