### ISSUE TITLE
master上如果停止和启动kube-scheduler

### ISSUE THREAD

**Issue by opcache** [Lentil1016/kubeadm-ha#49]
按这个项目部署了三台虚拟机，都正常，在其中一台执行systemctl stop docker
ps aux  |grep etc
看到有 kube-scheduler 和kube-controller-manager开头的进程
怎么正常关闭呢？我kill  pid 然后要怎么把这个启动起来 ？

**Comment by opcache** [comment]
systemctl restart keepalived
systemctl restart docker
systemctl restart kubelet
貌似这样可以恢复，作者有之前有遇到过吗 ？

**Comment by Lentil1016** [comment]
systemctl stop docker执行完之后应该不会再看到kube-scheduler和kube-controller-manager进程。至于杀了进程之后只需要把docker启动起来过一段时间kubelet就会把这些自动起起来。如果不想等的话也可以在启动docker后重启一下kubelet立刻刷新状态。重启keepalived是没必要的

**Comment by Lentil1016** [comment]
我将关闭这个问题，如有需要请重新开启
