### ISSUE TITLE
CIDR设置不合适

### ISSUE THREAD

**Issue by fanfengqiang** [Lentil1016/kubeadm-ha#5]
楼主设置pod网络的cidr为：CIDR=172.168.0.0/16
而这个网段并不是一个私网网段，私网网段有三个
A类：10.0.0.0/8
B类：172.16.0.0/12   -->  172.16.0.0/16~172.31.0.0/16
C类：192.168.0.0/16
而上述网段并不是这三个网段的子集，也就是说这个地址段与公网中的地址有重叠，这会造成pod访问公网地址时会有部分地址无法到达。

**Comment by Lentil1016** [comment]
@fanfengqiang 172.168.0.0/16 这一网段的IP都分配在美国，由于公司大体上是私有云，而且各个私有网段都占了，所以当时图方便选择了这个网段，但的确不适合作为开源的默认配置，我会马上修复。
