### ISSUE TITLE
kernel 4.18的离线源有吗？elrepo里只有4.4和5.0的，谢谢！

### ISSUE THREAD

**Issue by muercy** [Lentil1016/kubeadm-ha#56]
请问大家是怎么升级的？

**Comment by Lentil1016** [comment]
您好，可以使用我之前从elrepo中下载的4.18版本内核的rpm包，链接: https://pan.baidu.com/s/1DooJx9Jx6_qoFb-uNOCvug 提取码: bumr。

**Comment by muercy** [comment]
谢谢
