### ISSUE TITLE
请问哪里有执行脚本之前要做事项的教程？

### ISSUE THREAD

**Issue by iedwin** [Lentil1016/kubeadm-ha#57]
RT.
BTW: 之前LVS有BUG，不知道现在BUG解决了吗，还需要升级内核到4.19吗？

Thx.

**Comment by lentil1016** [comment]
[1.14.0版本部署文档](https://www.kubernetes.org.cn/5213.html)
不知道你说的bug是指哪个
kubernetes/kubernetes#70304 是4.19版本内核导致低于1.13.0版本的kubernetes无法开启ipvs模式，在kubernetes1.13.0中修复。
kubernetes/kubernetes#71071 1.13.0版本kube-proxy在IPVS模式下一段时间后停止更新规则，这个问题在1.13.2中修复。
我的文章中一般建议升级内核到最新版，如5.0.4。

**Comment by lentil1016** [comment]
如果没有更多疑问，可以关闭这个问题

**Comment by iedwin** [comment]
非常感谢！
这俩问题都算是，因为在1.13.0我记得有相关的issue提出来。
