### ISSUE TITLE
关于calico3.6.0中存在一些问题，已经再3.61中已修复。

### ISSUE THREAD

**Issue by wufenglinux** [Lentil1016/kubeadm-ha#59]
情爱的作者 您好，
您在中文社区遇到的3.6.0版本问题已经修复，请查收后校验，
https://github.com/projectcalico/calico/issues/2501#issuecomment-477657072

烦请在https://www.kubernetes.org.cn/5213.html此文档中更新calico的版本，谢谢！

**Comment by lentil1016** [comment]
@wufenglinux 还存在已知bug，但我暂时没有时间提PR

**Comment by lentil1016** [comment]
k8s-pod-network中旧的过期的ipam记录会让3.6.x中的calico-ipam initContainer陷入无限等待，导致calico无法启动，问题可以复现，我可能下周会在上游提issue或者PR，你要是有兴趣的话也可以替我提，calicoproject badge先到先得。我将关闭这个问题
