### ISSUE TITLE
您好，执行您的脚本出现无法通过VIP加入集群的报错

### ISSUE THREAD

**Issue by Ushijima-yanj** [Lentil1016/kubeadm-ha#60]
<code>error execution phase preflight: unable to fetch the kubeadm-config ConfigMap: failed to get config map: Get https://10.16.10.50:6443/api/v1/namespaces/kube-system/configmaps/kubeadm-config: dial tcp 10.16.10.50:6443: connect: connection refused</code>

然后查看keepalived的日志发现如下报错：
<code>
Apr 02 11:47:49 k8s-master1 Keepalived_healthcheckers[28292]: Remote Web server [10.16.10.91]:6443 succeed on service.
Apr 02 11:47:49 k8s-master1 Keepalived_healthcheckers[28292]: Adding service [10.16.10.91]:6443 to VS [10.16.10.50]:6443
Apr 02 11:47:49 k8s-master1 Keepalived_healthcheckers[28292]: IPVS (cmd 1159, errno 2): No such file or directory
</code>

内核我参照您搭建1.14那篇帖子更新过了，开启了IPVS
这个是我的cluster-info文件：

CP0_IP=10.16.10.91
CP1_IP=10.16.10.92
CP2_IP=10.16.10.93
VIP=10.16.10.50
NET_IF=eth0
CIDR=10.244.0.0/16

**Comment by lentil1016** [comment]
您好，请贴出以下命令的执行结果
```
nmap -Pn 10.16.10.91-93 -p 6443
nmap -Pn 10.16.10.50 -p 6443
```

**Comment by Ushijima-yanj** [comment]
[root@k8s-master1 ~]# nmap -Pn 10.16.10.91-93 -p 6443

Starting Nmap 6.40 ( http://nmap.org ) at 2019-04-02 13:00 CST
Nmap scan report for 10.16.10.91
Host is up (0.00023s latency).
PORT     STATE SERVICE
6443/tcp open  unknown

Nmap scan report for 10.16.10.92
Host is up (0.0012s latency).
PORT     STATE    SERVICE
6443/tcp filtered unknown
MAC Address: C6:66:2A:76:9E:C3 (Unknown)

Nmap scan report for 10.16.10.93
Host is up (0.0012s latency).
PORT     STATE    SERVICE
6443/tcp filtered unknown
MAC Address: 36:53:ED:72:98:38 (Unknown)

Nmap done: 3 IP addresses (3 hosts up) scanned in 3.03 seconds
[root@k8s-master1 ~]# nmap -Pn 10.16.10.50 -p 6443

Starting Nmap 6.40 ( http://nmap.org ) at 2019-04-02 13:00 CST
Nmap scan report for 10.16.10.50
Host is up (0.00020s latency).
PORT     STATE SERVICE
6443/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.39 seconds

**Comment by lentil1016** [comment]
`connect: connection refused`通常在对端TCP端口为`closed`的情况下报出，而在你的上一个回复中，`VIP:6443`端口是Open的，不可能报出`connect: connection refused`这个错误。因此很可能已经与最初错误提示发生时的情况有所不同，请在`master-1`上检查`apiserver`是否在持续重启
- 检查`docker ps -a`中是否存在已经退出的apiserver容器，如果有，请贴出该已退出容器的日志。
- 运行`kubectl get pods -n kube-system -w`，并贴出返回结果

**Comment by Ushijima-yanj** [comment]
![图片](https://user-images.githubusercontent.com/45476234/55379394-8b56a700-554f-11e9-9e96-d9febb8f2a0a.png)

![图片](https://user-images.githubusercontent.com/45476234/55379405-93aee200-554f-11e9-880b-0e51ae820fc8.png)



没有存在apiserver重启或退出的现象。。不过10.16.10.50:6443在master1上查看是打开的，在master2上运行却是关闭着的

[root@k8s-master2 ~]# nmap -Pn 10.16.10.91-93 -p 6443

Starting Nmap 6.40 ( http://nmap.org ) at 2019-04-02 14:02 CST
Nmap scan report for 10.16.10.91
Host is up (0.0012s latency).
PORT     STATE    SERVICE
6443/tcp filtered unknown
MAC Address: DE:E9:54:82:D0:26 (Unknown)

Nmap scan report for 10.16.10.93
Host is up (0.0012s latency).
PORT     STATE    SERVICE
6443/tcp filtered unknown
MAC Address: 36:53:ED:72:98:38 (Unknown)

Nmap scan report for 10.16.10.92
Host is up (0.00015s latency).
PORT     STATE  SERVICE
6443/tcp closed unknown

Nmap done: 3 IP addresses (3 hosts up) scanned in 2.43 seconds
[root@k8s-master2 ~]# nmap -Pn 10.16.10.50 -p 6443

Starting Nmap 6.40 ( http://nmap.org ) at 2019-04-02 14:02 CST
Nmap scan report for 10.16.10.50
Host is up (0.00022s latency).
PORT     STATE  SERVICE
6443/tcp closed unknown

**Comment by lentil1016** [comment]
@Ushijima-yanj 从master2上扫描master1的6443端口时返回了filtered，请关闭master1上的防火墙，如果是在公有云上，请额外检查安全组策略

**Comment by Ushijima-yanj** [comment]
I just cleared the firewall on three machines，it works for me! 滑天下之大稽，我一直认为是keepalived出了什么问题，看样子是我的问题:( 多谢多谢！
