### ISSUE TITLE
关于calico.yaml，官网提供的yaml总会有一个calico-kube-controllers这个deployment，为什么大佬的yaml没有这个呢

### ISSUE THREAD

**Issue by yangjie1993** [Lentil1016/kubeadm-ha#61]

**Comment by yangjie1993** [comment]
https://docs.projectcalico.org/v3.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml 如此所示

**Comment by lentil1016** [comment]
该controller是从v3.6版本才加入到manifests中，我提供的是官方v3.5版本的manifest，在[这里](https://github.com/lentil1016/kubeadm-ha/blob/master/calico)有注明来源。
关于为什么不使用v3.6，是因为我在v3.6的calico上遇到了一些plugin-cni的启动问题，plugin-cni读到以前集群的旧的network文件时会卡住。详情可见https://github.com/lentil1016/kubeadm-ha/issues/59#issuecomment-477951399

**Comment by lentil1016** [comment]
如果没有其他疑问的话可以关闭这个issue

**Comment by yangjie1993** [comment]
好的，多谢解答

**Comment by yangjie1993** [comment]
好的，多谢解答，有什么资料能够更好更深入的理解calico呢。。。。

**Comment by lentil1016** [comment]
我对calico的了解也很浅，只知道calico的overlay网络完全是通过linux FIB(具体起来应该是route+iptables)实现的，calico的服务本身主要工作是ipam，路由规则广播，路由表维护这些工作，容器网络包不过calico模块。
这篇文档说的比我细：https://docs.projectcalico.org/v3.6/reference/architecture/#content-main
