### ISSUE TITLE
1.14.0版本kubelet 问题

### ISSUE THREAD

**Issue by sudy1** [Lentil1016/kubeadm-ha#62]
1.14.0版本kubelet 问题，在系统日志里面出现大量的日志。
 Active: active (running) since Tue 2019-04-16 22:54:30 CST; 1h 6min ago
     Docs: https://kubernetes.io/docs/
 Main PID: 859 (kubelet)
    Tasks: 22
   Memory: 130.2M
   CGroup: /system.slice/kubelet.service
           └─859 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1

Apr 17 00:01:08 k8s-m1 kubelet[859]: W0417 00:01:08.884515     859 raw.go:87] Error while processing event ("/sys/fs/cgroup/memory/libcontainer_22369_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): readdirent: no such file or directory
Apr 17 00:01:08 k8s-m1 kubelet[859]: W0417 00:01:08.884549     859 raw.go:87] Error while processing event ("/sys/fs/cgroup/devices/libcontainer_22369_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/devices/libcontainer_22369_systemd_test_default.slice: no such file or directory
Apr 17 00:01:14 k8s-m1 kubelet[859]: W0417 00:01:14.693640     859 container.go:523] Failed to update stats for container "/libcontainer_22469_systemd_test_default.slice": open /sys/fs/cgroup/cpu,cpuacct/libcontainer_22469_systemd_test_default.slice/cpuacct.stat: no such file or directory, continuing to push stats
Apr 17 00:01:14 k8s-m1 kubelet[859]: W0417 00:01:14.717462     859 container.go:523] Failed to update stats for container "/libcontainer_22475_systemd_test_default.slice": failed to parse memory.memsw.usage_in_bytes - read /sys/fs/cgroup/memory/libcontainer_22475_systemd_test_default.slice/memory.memsw.usage_in_bytes: no such device, continuing to push stats
Apr 17 00:01:14 k8s-m1 kubelet[859]: W0417 00:01:14.748654     859 raw.go:87] Error while processing event ("/sys/fs/cgroup/blkio/libcontainer_22481_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/blkio/libcontainer_22481_systemd_test_default.slice: no such file or directory
Apr 17 00:01:14 k8s-m1 kubelet[859]: W0417 00:01:14.749910     859 raw.go:87] Error while processing event ("/sys/fs/cgroup/devices/libcontainer_22481_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/devices/libcontainer_22481_systemd_test_default.slice: no such file or directory
Apr 17 00:01:14 k8s-m1 kubelet[859]: W0417 00:01:14.752770     859 raw.go:87] Error while processing event ("/sys/fs/cgroup/blkio/libcontainer_22481_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/blkio/libcontainer_22481_systemd_test_default.slice: no such file or directory
Apr 17 00:01:14 k8s-m1 kubelet[859]: W0417 00:01:14.752807     859 raw.go:87] Error while processing event ("/sys/fs/cgroup/memory/libcontainer_22481_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/memory/libcontainer_22481_systemd_test_default.slice: no such file or directory
Apr 17 00:01:14 k8s-m1 kubelet[859]: W0417 00:01:14.752824     859 raw.go:87] Error while processing event ("/sys/fs/cgroup/devices/libcontainer_22481_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/devices/libcontainer_22481_systemd_test_default.slice: no such file or directory
Apr 17 00:01:18 k8s-m1 kubelet[859]: W0417 00:01:18.882369     859 container.go:523] Failed to update stats for container "/libcontainer_22530_systemd_test_default.slice": open /sys/fs/cgroup/cpu,cpuacct/libcontainer_22530_systemd_test_default.slice/cpuacct.usage_percpu: no such file or directory, continuing to push stats

请问怎么解决呢？

**Comment by lentil1016** [comment]
Duplicated, check https://github.com/kubernetes/kubernetes/issues/76531

**Comment by xxshuo** [comment]
yum -y install docker-ce-cli-18.09.9-3.el7.x86_64
 yum -y install docker-ce-18.09.9-3.el7.x86_64
更新docker 到18.09 
k8s 版本 --kubernetes-version v1.16.3 测试该问题已修复

**Comment by xxshuo** [comment]
yum -y install docker-ce-cli-18.09.9-3.el7.x86_64
 yum -y install docker-ce-18.09.9-3.el7.x86_64
> 更新docker 到18.09
> k8s 版本 --kubernetes-version v1.16.3 测试该问题已修复
