### ISSUE TITLE
关于高可用集群证书的问题 

### ISSUE THREAD

**Issue by yangjie1993** [Lentil1016/kubeadm-ha#65]
大佬，再打扰你一下关于高可用集群证书的问题。。之前再v1.11的时候是我在每台master上生成每个组件的如apiserver，etcd。100年证书，同时再用kubeadm alpha phase把节点标记成master之类

现在用kubeadm join 实现ha的话，我还要这么做么。。而且我还需要手动把每个master的etcd加到集群里，现在这个命令是帮你完成这个功能了是么

**Comment by lentil1016** [comment]
emmmm，集群证书方面，我使用的是默认的1年到期的证书，所以我不太清楚你说的100年的证书具体是怎么样的配置生成的。
其实kubernetes的certificates、还有kubeconfig格式已经很久没有变过了，如果你不想换pki的话，完全可以将旧集群的`/etc/kubernetes`文件夹下除了manifest文件夹以外的其他所有文件备份，然后使用新集群后，再把pki和kubeconfig还原成原来的，相当于只更新了manifests里的staticPods文件。不知道这是不是你想实现的效果。
关于kubernetes的pki，其实本质上就是普通的证书中设置了特定的CN值，详情可以参考[本页面](https://kubernetes.io/docs/setup/certificates/#configure-certificates-manually)

**Comment by yangjie1993** [comment]
@lentil1016 突然发现我kubelet报错了，说我用的cgroup driver用的是cgroupfs跟docker的不一样。看你的文章不是说现在都采用 systemd作为cgroup driver么。。而且你的 docker配置文件也是用的systemed
我是哪里没有配对么
failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"

**Comment by lentil1016** [comment]
请贴出以下命令的执行结果
```
docker info |grep -i cgroup
cat /etc/docker/daemon.json
cat /var/lib/kubelet/config.yaml | grep cgroup
```

**Comment by yangjie1993** [comment]
![b4f014cd](https://user-images.githubusercontent.com/18029405/56883243-a78b2c80-6a98-11e9-9112-e1dcf713c967.png)
/var/lib/kubelet/config.yaml 不存在

**Comment by lentil1016** [comment]
```
cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
cat /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
cat /var/lib/kubelet/kubeadm-flags.env
```

**Comment by yangjie1993** [comment]
![3fdcc386](https://user-images.githubusercontent.com/18029405/56883551-a0185300-6a99-11e9-991b-b3e3c95f26b1.png)

**Comment by lentil1016** [comment]
考虑到kubelet启动依赖于config.yaml文件，我不认为你的集群建立成功了，请尝试重新执行脚本创建集群，并注意创建过程是否存在报错。

**Comment by lentil1016** [comment]
我将关闭这个问题，有需要请重新开启

**Comment by yangjie1993** [comment]
行吧。。经过一番排查应该是我生成的证书有问题，我重新生成证书后已经解决的相关问题。。
不过现在有个新的问题
pause容器在worker节点无法下载
关于pause这个容器应该是k8s用于监听node。。是依靠 kubelet下载的
我并没有使用你的 自带harbor仓库而是把镜像上传到公司的镜像仓库。。
但是kubelet无法下载pause镜像，原因可能是公司的镜像仓库有权限限制，但是手动docker pull 是可以的。。只要docker login过就行
当然worker上的其他镜像可以通过在k8s集群内配置secret去拉取私有仓库的镜像。。
但是pause似乎是kubelet管理。。不知道大佬是否遇到相关的问题
当然，是不是用你的harbor镜像仓库就不会有这个问题呢
@lentil1016

**Comment by lentil1016** [comment]
你说的对，pause容器由kubelet隐式启动的容器，每个pod一个，pause容器就是pod的基底。

但kubelet并不是亲自拉取镜像，而是通过cri控制docker/containerd拉取镜像

因此，如果需要在worker机器上下载pause镜像，只要先让worker机器上的docker登陆到公司镜像仓库，使得worker机器可以直接通过docker pull拉取该镜像，随后kubelet便可以正常运行。

**Comment by yangjie1993** [comment]
> 你说的对，pause容器由kubelet隐式启动的容器，每个pod一个，pause容器就是pod的基底。
> 
> 但kubelet并不是亲自拉取镜像，而是通过cri控制docker/containerd拉取镜像
> 
> 因此，如果需要在worker机器上下载pause镜像，只要先让worker机器上的docker登陆到公司镜像仓库，使得worker机器可以直接通过docker pull拉取该镜像，随后kubelet便可以正常运行。

- -这就是关键。。我已经login完了。。新的worker节点还是无法自动拉去pause容器。。我得手动输入命令docker pull 才行。。

**Comment by lentil1016** [comment]
请贴出下面命令在异常机器上的执行结果
```
systemctl stop kubelet
systemctl restart docker
docker rmi k8s.gcr.io/pause:3.1
docker pull k8s.gcr.io/pause:3.1
docker images|grep pause
docker rmi k8s.gcr.io/pause:3.1
systemctl start kubelet
sleep 20
docker images|grep pause
docker ps
```

**Comment by yangjie1993** [comment]
要把worker节点上的k8s删除么，就是reset
