### ISSUE TITLE
关于VIP那台机器得设置，是怎么设置呢？

### ISSUE THREAD

**Issue by ryouaki** [Lentil1016/kubeadm-ha#66]
关于VIP那台机器得设置，是怎么设置呢？

**Comment by lentil1016** [comment]
我不确定我理解了你的描述，VIP不是一台机器，VIP只是一个IP地址，同一时间由高可用集群中的某一台机器取得。所以VIP的机器就是三个kubernetes master中的某一个，三个master只需要设置好keepalived，不需要额外设置。具体细节请参考vrrp协议。

**Comment by ryouaki** [comment]
我是看了你在k8s中文得文章。里面提到一个vip得83得机器。但是却没有任何关于这台机器得配置说明。
只是直接运行了这里得ha脚本。

那么也就是说负责vip得那台服务器，只要安装了keepalive和haproxy即可。其它就不需要额外设置了？

然后在master运行你这里得脚本。

**Comment by lentil1016** [comment]
VIP的全称是Virtual IP，没有一台专门的机器负责VIP，不需要为83安排一台专门的机器，keepalived运行时将把83按优先级绑定在80，81或82上，请先了解VRRP协议，以及VIP的原理。

**Comment by lentil1016** [comment]
我将关闭这个问题，有需要请重新开启
