### ISSUE TITLE
kubernetes: master init node localhost.localdomain not found

### ISSUE THREAD

**Issue by chenliu1993** [Lentil1016/kubeadm-ha#67]
Hi,
   I am using kubeadm init to init one master node based on one VM. But during the process, node"localhost.localdomain" nout found problem always shows up. 
   My /etc/hosts:
   **127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
   ::1   localhost localhost.localdomain localhost4 localhost4.localdomain4
   192.168.5.130 localhost.localdomain**
    The docekr version os 18.06-ce, kubernetes version is v1.13.4
    The kernel is based on linux-4.9.137, self compiled. These are all the modules the kernel has:
![image](https://user-images.githubusercontent.com/13761170/57667063-decf1100-7634-11e9-82e6-8ec610317885.png)
    Some solutions says that kubernetes use its own dns to resolv the master name, not the /resolv.conf. Is it true?
![image](https://user-images.githubusercontent.com/13761170/57667018-a6c7ce00-7634-11e9-9f41-66f79f0feabc.png)
This is the output of systemctl status kubelet -l:

Loaded: loaded (/kind/systemd/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           ΓööΓöÇ10-kubeadm.conf
   Active: active (running) since Tue 2019-05-14 10:40:31 UTC; 4min 7s ago
     Docs: http://kubernetes.io/docs/
 Main PID: 1212 (kubelet)
   CGroup: /system.slice/kubelet.service
           ΓööΓöÇ1212 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=cgroupfs --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1 --fail-swap-on=false

May 14 10:44:39 localhost.localdomain kubelet[1212]: E0514 10:44:39.097781    1212 kubelet.go:2266] node "localhost.localdomain" not found
May 14 10:44:39 localhost.localdomain kubelet[1212]: E0514 10:44:39.155161    1212 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-apiserver-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 14 10:44:39 localhost.localdomain kubelet[1212]: E0514 10:44:39.155183    1212 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "kube-apiserver-localhost.localdomain_kube-system(a9b7dd24584050387fb803d4e69019ca)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-apiserver-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 14 10:44:39 localhost.localdomain kubelet[1212]: E0514 10:44:39.155192    1212 kuberuntime_manager.go:662] createPodSandbox for pod "kube-apiserver-localhost.localdomain_kube-system(a9b7dd24584050387fb803d4e69019ca)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-apiserver-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 14 10:44:39 localhost.localdomain kubelet[1212]: E0514 10:44:39.155223    1212 pod_workers.go:190] Error syncing pod a9b7dd24584050387fb803d4e69019ca ("kube-apiserver-localhost.localdomain_kube-system(a9b7dd24584050387fb803d4e69019ca)"), skipping: failed to "CreatePodSandbox" for "kube-apiserver-localhost.localdomain_kube-system(a9b7dd24584050387fb803d4e69019ca)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-apiserver-localhost.localdomain_kube-system(a9b7dd24584050387fb803d4e69019ca)\" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod \"kube-apiserver-localhost.localdomain\": Error response from daemon: cgroups: cgroup deleted: unknown"
May 14 10:44:39 localhost.localdomain kubelet[1212]: E0514 10:44:39.168221    1212 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-scheduler-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 14 10:44:39 localhost.localdomain kubelet[1212]: E0514 10:44:39.168243    1212 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "kube-scheduler-localhost.localdomain_kube-system(4b52d75cab61380f07c0c5a69fb371d4)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-scheduler-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 14 10:44:39 localhost.localdomain kubelet[1212]: E0514 10:44:39.168252    1212 kuberuntime_manager.go:662] createPodSandbox for pod "kube-scheduler-localhost.localdomain_kube-system(4b52d75cab61380f07c0c5a69fb371d4)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-scheduler-localhost.localdomain": Error response from daemon: cgroups: cgroup deleted: unknown
May 14 10:44:39 localhost.localdomain kubelet[1212]: E0514 10:44:39.168281    1212 pod_workers.go:190] Error syncing pod 4b52d75cab61380f07c0c5a69fb371d4 ("kube-scheduler-localhost.localdomain_kube-system(4b52d75cab61380f07c0c5a69fb371d4)"), skipping: failed to "CreatePodSandbox" for "kube-scheduler-localhost.localdomain_kube-system(4b52d75cab61380f07c0c5a69fb371d4)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-scheduler-localhost.localdomain_kube-system(4b52d75cab61380f07c0c5a69fb371d4)\" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod \"kube-scheduler-localhost.localdomain\": Error response from daemon: cgroups: cgroup deleted: unknown"
May 14 10:44:39 localhost.localdomain kubelet[1212]: E0514 10:44:39.198628    1212 kubelet.go:2266] node "localhost.localdomain" not found

The command is "kubeadm init --ignore-preflight-errors=all --config=kubeadm.conf --skip-token-print --v=6"

The content of kubeadm.conf is:
   apiServer:
  certSANs:
   localhost
apiVersion: kubeadm.k8s.io/v1beta1
clusterName: simple
controllerManager:
  extraArgs:
    enable-hostpath-provisioner: "true"
kind: ClusterConfiguration
kubernetesVersion: v1.13.4
metadata:
  name: config

apiVersion: kubeadm.k8s.io/v1beta1
bootstrapTokens:
- token: abcdef.0123456789abcdef
kind: InitConfiguration
localAPIEndpoint:
  bindPort: 6443
metadata:
  name: config

apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
metadata:
  name: config

apiVersion: kubelet.config.k8s.io/v1beta1
evictionHard:
  imagefs.available: 0%
  nodefs.available: 0%
  nodefs.inodesFree: 0%
imageGCHighThresholdPercent: 100
kind: KubeletConfiguration
metadata:
  name: config

apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
metadata:
  name: config

**Comment by chenliu1993** [comment]
This is part of the output of "journalctl -xeu kubelet":
![image](https://user-images.githubusercontent.com/13761170/57667272-864c4380-7635-11e9-8807-997e1d970c3f.png)
localhost.localdomain can't found itself......
I tried this under CentOS 7 but it worked...

**Comment by lentil1016** [comment]
Is using "localhost. localdomain" as the node name necessary for you? I'm really confused.
What is the result of `hostname` on your VM? 'localhost' or 'localhost.domain'? Why 'localhost.domain' is not on your `apiserver.certSANs` list?

**Comment by lentil1016** [comment]
Your log says that your `apiserver` isn't running, please check container logs, find out why the `apiserver` container is failed. Nothing in K8s will work without `apiserver` running healthily.

**Comment by chenliu1993** [comment]
> Is using "localhost. localdomain" as the node name necessary for you? I'm really confused.
> What is the result of `hostname` on your VM? 'localhost' or 'localhost.domain'? Why 'localhost.domain' is not on your `apiserver.certSANs` list?

no, it is not necessary.
hostname on VM is localhost.localdomain.
But on CentOS 7 the apiserver.certSANs is the same and kubeadm init works fine. And the CentOS's hostname is also localhost.localdomain......

**Comment by chenliu1993** [comment]
> Your log says that your `apiserver` isn't running, please check container logs, find out why the `apiserver` container is failed. Nothing in K8s will work without `apiserver` running healthily.

Okay, I will look into this matter. 
![image](https://user-images.githubusercontent.com/13761170/57670656-d087f180-7642-11e9-91f0-593d84cc4e22.png)

**Comment by chenliu1993** [comment]
This is the output of docker ps -a | grep kube:
![image](https://user-images.githubusercontent.com/13761170/57672566-3f694880-764b-11e9-949d-5e50e6e8a2e6.png)
apiserver not running, even created.

**Comment by lentil1016** [comment]
That's not right.
Try run `docker pull k8s.gcr.io/kube-apiserver:v1.13.4` on that VM, see if dockerd is not able to pull the desired image.
Also run `systemctl status kubelet` to make sure that `kubelet` is running correctly.

**Comment by chenliu1993** [comment]
> That's not right.
> Try run `docker pull k8s.gcr.io/kube-apiserver:v1.13.4` on that VM, see if dockerd is not able to pull the desired image.
> Also run `systemctl status kubelet` to make sure that `kubelet` is running correctly.

I tried as you suggested.
The apiserver image is okay.
Before kubeadm init, systemctl status kubelet show kubelet is loaded and activating. After kubeadm init, shows kubelet is active but with the errors "node not found."

**Comment by chenliu1993** [comment]
> That's not right.
> Try run `docker pull k8s.gcr.io/kube-apiserver:v1.13.4` on that VM, see if dockerd is not able to pull the desired image.
> Also run `systemctl status kubelet` to make sure that `kubelet` is running correctly.

This is the docker image ls shows:
![image](https://user-images.githubusercontent.com/13761170/57678066-f5885e80-765a-11e9-8f65-c0f389971f4d.png)

**Comment by chenliu1993** [comment]
> That's not right.
> Try run `docker pull k8s.gcr.io/kube-apiserver:v1.13.4` on that VM, see if dockerd is not able to pull the desired image.
> Also run `systemctl status kubelet` to make sure that `kubelet` is running correctly.

**This is the output of systemctl status kubelet -l after kubeadm init fails:**

ΓùÅ kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/kind/systemd/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           ΓööΓöÇ10-kubeadm.conf
   Active: active (running) since Tue 2019-05-14 15:22:44 UTC; 4min 0s ago
     Docs: http://kubernetes.io/docs/
 Main PID: 1110 (kubelet)
   CGroup: /system.slice/kubelet.service
           ΓööΓöÇ1110 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=cgroupfs --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1 --fail-swap-on=false

May 14 15:26:44 localhost.localdomain kubelet[1110]: E0514 15:26:44.332524    1110 kubelet.go:2266] node "localhost.localdomain" not found
May 14 15:26:44 localhost.localdomain kubelet[1110]: E0514 15:26:44.439406    1110 kubelet.go:2266] node "localhost.localdomain" not found
May 14 15:26:44 localhost.localdomain kubelet[1110]: E0514 15:26:44.540397    1110 kubelet.go:2266] node "localhost.localdomain" not found
May 14 15:26:44 localhost.localdomain kubelet[1110]: E0514 15:26:44.641834    1110 kubelet.go:2266] node "localhost.localdomain" not found
May 14 15:26:44 localhost.localdomain kubelet[1110]: E0514 15:26:44.680065    1110 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.5.130:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dlocalhost.localdomain&limit=500&resourceVersion=0: dial tcp 192.168.5.130:6443: connect: connection refused
May 14 15:26:44 localhost.localdomain kubelet[1110]: E0514 15:26:44.680111    1110 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://192.168.5.130:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.5.130:6443: connect: connection refused
May 14 15:26:44 localhost.localdomain kubelet[1110]: E0514 15:26:44.686715    1110 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Get https://192.168.5.130:6443/api/v1/nodes?fieldSelector=metadata.name%3Dlocalhost.localdomain&limit=500&resourceVersion=0: dial tcp 192.168.5.130:6443: connect: connection refused
May 14 15:26:44 localhost.localdomain kubelet[1110]: E0514 15:26:44.746818    1110 kubelet.go:2266] node "localhost.localdomain" not found
May 14 15:26:44 localhost.localdomain kubelet[1110]: E0514 15:26:44.847931    1110 kubelet.go:2266] node "localhost.localdomain" not found
May 14 15:26:44 localhost.localdomain kubelet[1110]: E0514 15:26:44.948379    1110 kubelet.go:2266] node "localhost.localdomain" not found

**Comment by lentil1016** [comment]
This might help you a little:
https://github.com/kubernetes/kubeadm/issues/881#issuecomment-396638808
https://github.com/kubernetes/kubeadm/issues/1082

It seems the hostnames like `localhost.localdomain` or `test.whatever` are not abled to register to apiserver. This issue should gone if you change your hostname to `localhost`.

**Comment by lentil1016** [comment]
I'll close this issue, feel free to reopen if you need.
