### ISSUE TITLE
metrics-server 不支持docker使用systemd么

### ISSUE THREAD

**Issue by yangjie1993** [Lentil1016/kubeadm-ha#68]
安装metrics-server 

报错
截图如下：
![815d93bb](https://user-images.githubusercontent.com/18029405/57992518-29de9d80-7ae7-11e9-9fdc-a1d3406963f8.png)

我docker使用的是systemd

**Comment by lentil1016** [comment]
![image](https://user-images.githubusercontent.com/12230071/57992648-dd479200-7ae7-11e9-8222-55f1b20ec6ad.png)
我没能复现这个问题

**Comment by lentil1016** [comment]
另外需要明确一点，你在describe中看到的信息是kubelet给出的，这个时候容器还没有运行起来，因此是机器环境，kubelet或docker三者中的某一个有问题，和metrics-server应用无关，请检查master02机器本身。

**Comment by yangjie1993** [comment]
failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"

好像还是这个问题
然后我执行了
docker info |grep -i cgroup
cat /etc/docker/daemon.json
cat /var/lib/kubelet/config.yaml | grep cgroup

![dd942441](https://user-images.githubusercontent.com/18029405/57993489-bee39580-7aeb-11e9-846d-747c23f5ff3b.png)

其中/var/lib/kubelet/config.yaml 的cgroup driver是我刚改成 systemd的。。好像一开始默认是cgroupfs？

**Comment by lentil1016** [comment]
@yangjie1993 你执行命令的机器是master01，请检查master02

**Comment by yangjie1993** [comment]
> @yangjie1993 你执行命令的机器是master01，请检查master02

现在都一样了。。。因为所有的kubelet都起不起来了。。包括mater01的

**Comment by yangjie1993** [comment]
> > @yangjie1993 你执行命令的机器是master01，请检查master02
> 
> 现在都一样了。。。因为所有的kubelet都起不起来了。。包括mater01的

master02 的 driver是cgroups

**Comment by lentil1016** [comment]
虽然和你的问题没关系，但我非常好奇，连kubelet都没启动成功，apiserver肯定没启动，那你是怎么截到一楼那张图的。

**Comment by lentil1016** [comment]
kubelet的配置除了`config.yaml`外还有一个大概叫`kubeadm-env`的文件，另外`/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf`也需要看一看。

**Comment by yangjie1993** [comment]
> 虽然和你的问题没关系，但我非常好奇，连kubelet都没启动成功，apiserver肯定没启动，那你是怎么截到一楼那张图的。

应该是这样的。。。我matser01因为疏忽docker是使用cgroup的。。所以导致后面mater02跟master03 kubelet异常，我发现后修改mater01 的docker为systemd后重启，但是跟kubelet的配置的不一样所以导致现在kubulet启动不能。。所以现在看看可不可以通过修改kubelet的参数来正常启动kubelet。。。

**Comment by lentil1016** [comment]
理论上来说单个机器上的cgroup配置不会影响到另一台机器。一个集群里完全可以一半机器用systemd另一半用cgroupfs，只要保证kubelet和dockerd配置使用同一种控制器即可。

**Comment by yangjie1993** [comment]
> 理论上来说单个机器上的cgroup配置不会影响到另一台机器。一个集群里完全可以一半机器用systemd另一半用cgroupfs，只要保证kubelet和dockerd配置使用同一种控制器即可。

是呀。。。但是kubelet是cgroup是按照是什么来定的呢。。我现在修改了/var/lib/kubelet/config.yaml
的cgroup还是提示我kubelet跟docker的不一样。。好像没有生效的样子

**Comment by lentil1016** [comment]
请检查`/var/lib/kubelet/kubeadm-flag.env`

**Comment by yangjie1993** [comment]
是systemd

> 请检查`/var/lib/kubelet/kubeadm-flag.env`

--cgroup-driver=systemd

**Comment by lentil1016** [comment]
`/var/lib/kubelet/kubeadm-flag.env`是systemd的envFile，修改过之后还需要执行`systemctl daemon-reload`

**Comment by yangjie1993** [comment]
> `/var/lib/kubelet/kubeadm-flag.env`是systemd的envFile，修改过之后还需要执行`systemctl daemon-reload`

都执行过了= =

**Comment by lentil1016** [comment]
那能不能不要等我说完了你再告诉我。。。

**Comment by lentil1016** [comment]
谁知道你的环境什么样你做了什么操作

**Comment by lentil1016** [comment]
请给出复现条件，或者给出你认为有关系的所有信息

**Comment by yangjie1993** [comment]
> 请给出复现条件，或者给出你认为有关系的所有信息

应该是我的问题我重新安装试试
