### ISSUE TITLE
keepalive+LVS可以正常工作?

### ISSUE THREAD

**Issue by guoh1988** [Lentil1016/kubeadm-ha#7]
按照楼主部署keepalvied+lvs 
1.persistence_timeout 50 这个是50S时间是不是很长不能达到负载均衡
2.还有这边用curl -k https://10.130.29.83:6443 这边好像只能访问到10.130.29.80的这个apiserver，其他两个是出现无法解析，并没有实现轮循。

**Comment by Lentil1016** [comment]
@guoh1988 

您好，感谢报告该问题。

首先

> 1.persistence_timeout 50 这个是50S时间是不是很长不能达到负载均衡

据我所知Keepalived实现的并不是负载均衡，而是主备高可用，虚IP同一时间只能绑定到一台机器上。在我的部署方案中，apiserver是主备模式，而不是负载均衡模式。在我的部署文档中提到的LVS实际上指的是kube-proxy使用ip_vs模式代替了iptables。回到keepalived的配置，我尚不清楚`persistence_timeout`这个配置的应用场景，只是使用了网上推荐的配置值。

> 2.还有这边用curl -k https://10.130.29.83:6443 这边好像只能访问到10.130.29.80的这个apiserver，其他两个是出现无法解析，并没有实现轮循。

这是一个已知问题问题，遗憾的是，我对VRRP知之甚少，所以我暂时还不知道造成这个问题的根本原因。我最好的猜测是keepalived需要一段时间来进行网关层面的广播和协商，但这似乎并不能很好的解释我看到的现象。，以下仅为我在自己的环境上对该问题进行Debug的经历，希望对你有所帮助：

- VIP被绑定在`master-01`上，在`master-01`上`curl -kL --insecure https://￥{VIP}:6443/healthz`，返回`ok`。
- 在`master-02`和`master-03`上执行相同命令时，返回`No route to host`，然而`ssh ${VIP}`可以连接到`master-01`，并且执行`nmap -Pn ${VIP}`扫描虚IP，能得到6443端口正常开启的结果。
- 尝试删除keepalived.conf中健康检查部分配置，问题并没有得到解决。
- 重复重启各个节点上的keepalived，该问题得到解决。

如果你的情况与我不同，或者我的经历没有解决你的问题，请让我知道，谢谢。

**Comment by Lentil1016** [comment]
你好，我昨天重新了解了一下keepalived的相关知识，发现是我之前的理解有误，我已经通过 #8 这个PR在各个分支上提交了修复，应该和你所预期的修改基本相符。

https://github.com/Lentil1016/kubeadm-ha/blob/62e9c999c5e25dd22afac0f5ca53b6a28b318be1/kubeha-gen.sh#L125-L131

之前是我的配置错误造成了我误以为需要重启，目前的部署已经正常，不再需要等待或重启，也不再出现路由失败的情况。

关于问题3，我之前没有测试，我会尽快找没有开发任务的时间确认一下，如果发现有问题，我会另开一个Issue并告知你。
