### ISSUE TITLE
部署HA Master的问题

### ISSUE THREAD

**Issue by lixinglin213** [Lentil1016/kubeadm-ha#71]
部署版本为1.13.0的k8s集群

# 创建集群信息文件
echo """
CP0_IP=10.130.29.80
CP1_IP=10.130.29.81
CP2_IP=10.130.29.82
VIP=10.130.29.83
NET_IF=eth0
CIDR=10.244.0.0/16
""" > ./cluster-info

你好，有这样一个步骤，请问CIDR我应该怎么配置呢？假如我在公司内网配置k8s集群。内网ip为172.16.14.xxx
是否应该配置为172.244.0.0/16呢？

**Comment by lentil1016** [comment]
通常不会将CIDR配置为与内网网段~~不~~重合的网段，CIDR最终会被kubernetes用作pod-cidr，也即用于为Pod分配IP的IP pool，如果与实际的内网网段重合，在不做特殊配置的情况下会造成路由问题，导致集群容器网络不通。

**Comment by lentil1016** [comment]
[kubernetes set service cidr and pod cidr the same
](https://stackoverflow.com/questions/45903123/kubernetes-set-service-cidr-and-pod-cidr-the-same)
> You do have to reserve both the pod-network range and the service network range. You can't use those on your LAN (and you can't have routes to it).

**Comment by lixinglin213** [comment]
建议配置和内网一个网段的是吧，那如果配置为172.244.0.0/16 ，会不会创建pod的时候为pod分配的ip和内网实际的ip一样而造成冲突呢

**Comment by lentil1016** [comment]
上面写错了，请不要配置成同一网段

**Comment by lixinglin213** [comment]
你有在内网部署集群的经验吗？192.240.0.0/16和10.240.0.0/16这两个哪个会更合适呢

**Comment by lentil1016** [comment]
192.240.0.0/16是公网

**Comment by lixinglin213** [comment]
还是没太明白这个意义，以及最佳实践应该是怎样的，我需要再去多查一下资料

**Comment by lentil1016** [comment]
这个配置在小于255台机器的集群里没有什么最佳实践可言，就只是规划一个网段供cni plugin给容器分配IP用，像calico这种方案就是默认给每个node instance分配一个/24的pool，这个节点内的容器都在这个pool下拿IP，对于小规模的集群随便一个/16的网段就完全够用了，至于具体选用哪个网段，只要网段是可用的，那都完全是等价的。

**Comment by lixinglin213** [comment]
感谢你的解答，大致明白了，集群机器应该会控制在10台以内，用10.244.0.0/16 就可以
